### ISSUE TITLE
Add a Current Limit to All Moteus Controllers

### ISSUE THREAD

**Issue by VladimirKupryukhin** [TrickfireRobotics/urc-2023#52]
# Context
The Moteus Controllers have a config, and one of these options is to limit the current. We had most likely fried a controller in the past because there was no limit

# What to do
Go through all controllers and put a reasonable current on the controllers. No more than 10A for sure; make sure you consider the operating current for the motor and the Moteus controller when selecting the limit

**Comment by loukylor** [comment]
The [moteus python examples](https://github.com/mjbots/moteus/blob/66ddade0c624daf57e747cd738afd2efbcd3876c/lib/python/examples/diagnostic_protocol.py#L34) include an example on how to set config values. We'd have to expose this functionality somewhere in the moteus controllers. I was thinking something like add `**kwargs` for config values in the moteus controller constructor. However, we could also expose a `set_config` method since, [according to the reference page](https://github.com/mjbots/moteus/blob/66ddade0c624daf57e747cd738afd2efbcd3876c/docs/reference.md#c-configurable-values), config values take effect immediately.

**Comment by VladimirKupryukhin** [comment]
As of right now, there are current limits to the following motors:
- All drivebase controllers are limited to 10A
- Turntable, Shoulder, Elbow controllers are limited to 10A

**Comment by loukylor** [comment]
fixed by #62
